### ISSUE TITLE
What is the ugliest URL you've ever seen?

### ISSUE THREAD

**Issue by tigt** [adactio/ama#1]

**Comment by adactio** [comment]
Ooh, good question!

I can't remember any one particular bad URL that sticks in my mind, but then, that's one of the things that make a bad URL bad: lack of memorability.

I do remember when a lot of publishing sites were using the same CMS (back in the 90s/early 2000s), the name of which escapes me, but it would generate URLs entirely with overly verbose query strings and no slashes.

I was reminded of that when Twitter and others went through their demented period of hashbang URLs. Remember? twitter.com/#!/path/which/is/not/actually/a/path

Even though they eventually moved away from that structure, Twitter will need to maintain client side routing in perpetuity if it wants to keep inbound links from that time working (the server never sees anything from # onwards).

So depending on the long-term effects, one of the ugliest URLs may turn out to be <https://twitter.com/#!/adactio>
