### ISSUE TITLE
But these AMAs are on Github!

### ISSUE THREAD

**Issue by jimniels** [adactio/ama#2]
I know this tends to be you:

![Indie web](https://cdn.meme.am/cache/instances/folder718/51827718.jpg)

So as a proponent of owning your own data and the indie web I'm curious why you decided to do this on-going AMA on GitHub as opposed to, say, adactio.com? I could probably guess at the reasoning there, so let me also ask: do you plan on somehow saving and storing these questions/answers back to adactio so that they will live on indefinitely? Or are you just not really that interested in that data?

**Comment by adactio** [comment]
> I could probably guess at the reasoning there, so let me also ask: do you plan on somehow saving and storing these questions/answers back to adactio so that they will live on indefinitely?

Bingo! I'll be putting the good stuff on my blog. If nothing else, I hope that these AMA questions will be good fodder for prompting blog posts.

**Comment by jimniels** [comment]
> good fodder for prompting blog posts

There's an idea: how you automated saving these question over to your blog (assuming you use the GitHub API and that kind of thing is possible).

**Comment by adactio** [comment]
I don't want to put all of them on my blog, just the good ones.
