### ISSUE TITLE
Routine

### ISSUE THREAD

**Issue by jleiva** [adactio/ama#4]
You're always writing, coding, speaking, etc, can you talk a little about your routine?

**Comment by adactio** [comment]
It might look like I’m always writing, coding, and speaking, but I’m actually not very productive—I’m quite a lazy person by nature. But the difference is that I try to openly document what I’m up to. So I think that gives the impression that I’m doing a lot, when really it’s not the case: I give maybe one conference talk a month, and I do a bit of coding here or there. It’s true that I try to write a lot, but at this point that doesn’t feel like working. I spend a *lot* more time reading than writing: probably a ratio of ten to one.

As for a routine, well, let's see... Assuming I'm not travelling to give a conference talk, I get up around 8am, and do some stuff from home. That might be checking emails or Twitter. Then I head into work sometime around 10-10:30am. I'll read, write, and try to do any tasks that are on my plate, although I'm terrible procrastinator. One way I've found to trick myself is to procrastinate by doing something else that I'm also supposed to get done.

I'm very lucky to have a lot of freedom in how I spend my time and what I spend it on. For as much as I spend time goofing off on the internet, it comes in handy further down the line: something I read or linked to ends up being useful in a meeting a month later, for example.

Anyway, all this is to say that I do a lot *less* than most people I know (especially my colleagues at work), but I do a lot *more* writing and sharing about it.
